
ktor:
  application:
    modules:
      - org.burgas.ApplicationKt.module
  deployment:
    port: 9010
  postgres:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6000/construction_service_db
    user: postgres
    password: postgres
  redis:
    host: localhost